name: CI Pipeline
run-name: CI Pipeline of ${{ github.ref_name }}

on:
  push:
    branches:
      - "*"

jobs:
  UT_of_vending-machine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Set up Java 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: UT
        working-directory: vending-machine
        run: mvn clean test

  AT_of_vending-machine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Set up Java 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Install
        run: mvn clean install -Dmaven.test.skip=true

      - name: AT
        working-directory: vending-machine-acceptance-test
        run: mvn clean test
